### ISSUE TITLE
Wrong constant in zoneintervaltransition description

### ISSUE THREAD

**Issue by spazmodius** [nodatime/nodatime.org#101]
https://nodatime.org/developer/tzdb-file-format

The datatype `zoneintervaltransition` is described as possibly containing 

> number of minutes is in the range [**1048576**, Int32.MaxValue]

However, the [corresponding constant in nodatime is **2097152**](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/TimeZones/IO/DateTimeZoneWriter.cs#L46).

**Comment by jskeet** [comment]
Thanks, will fix it now.

**Comment by jskeet** [comment]
It should be picked up when the regular web site build happens tomorrow. (Although it's been a while since any changes have been needed, so it's entirely feasible that the automation will need some TLC.)

Thanks for spotting this - and I'm astonished that you did. If you're trying to use the same format for anything else, do let me know if I can help :)
